language: rust
sudo: false
cache: cargo
rust: stable
os: linux

jobs:
  include:
    - stage: publish
      script: cargo install mdbook
      script: mdbook build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./book
        on:
          branch: master