language: rust
sudo: false
cache: cargo
rust: stable
os: linux

jobs:
  include:
    - stage: publish
      if: branch = master
      script: 
        - cargo install mdbook
        - mdbook build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./book