# https://rust-lang.github.io/mdBook/format/config.html

[book]
title = "mdBook Test"
description = "The example book covers examples."
authors = ["Christoph Grabo", "and friends"]
language = "en"
# source = "src"

[rust]
edition = "2018"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/asaaki/mdBook-test"
curly-quotes = true
mathjax-support = true

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 1
